---
title: "STA304 final"
author: "Jinli Xu & Yichen Duo"
date: '2022-03-20'
output: pdf_document
abstract: "Your adujcnej"
bibliography: ref_list.bib
---
```{r 100,message=FALSE,echo=FALSE,warning=FALSE}
library(tidyverse)
library(kableExtra)
library(rms)
AA234RAH <- read_csv("AA234RAH.csv")
head(AA234RAH)
```

```{r 101,fig.cap="General Health and Cyber bullying", fig.width=6, fig.height=5,message=FALSE,echo=FALSE,warning=FALSE}
a = sum(AA234RAH$cbu_140==1)
b = sum(AA234RAH$cbu_140==2)
c = sum(AA234RAH$cbu_140==6)
cbu110_150table <- AA234RAH %>% filter(!is.na(cbu_140)) %>% 
  group_by(srh_110) %>% summarise(yes = sum(cbu_140 == 1), no = sum(cbu_140 == 2),
                                  valid_skip = sum(cbu_140 == 6))
knitr::kable(cbu110_150table, caption = "General Health and Cyber bullying")
```

```{r 102,fig.cap="Mental Health and Cyber bullying", fig.width=6, fig.height=5,message=FALSE,echo=FALSE,warning=FALSE}
cbu115_150table <- AA234RAH %>% 
  group_by(srh_115) %>% summarise(yes = sum(cbu_140 == 1), 
                                  no = sum(cbu_140 == 2),
                                  valid_skip = sum(cbu_140 == 6))
knitr::kable(cbu115_150table,caption = "Mental Health and Cyber bullying")
```

```{r 103,fig.cap="about mental health of people broup by encounter in cyber bullying", fig.width=6, fig.height=5,message=FALSE,echo=FALSE,warning=FALSE}
cexsrh115table <- AA234RAH %>% 
  group_by(cbu_110) %>% summarise(men1 = sum(srh_115 == 1), 
                                  men2 = sum(srh_115 == 2),
                                  men3 = sum(srh_115 == 3),
                                  men4 = sum(srh_115 == 4),
                                  men5 = sum(srh_115 == 5))
knitr::kable(cexsrh115table)
```

```{r 107,fig.cap="about mental health",message=FALSE,echo=FALSE,warning=FALSE}
AA234RAH$mental[AA234RAH$srh_115==1] <- "Exellent"
AA234RAH$mental[AA234RAH$srh_115==2] <- "Very good"
AA234RAH$mental[AA234RAH$srh_115==3] <- "Good"
AA234RAH$mental[AA234RAH$srh_115==4] <- "Fair"
AA234RAH$mental[AA234RAH$srh_115==5] <- "Poor"
AA234RAH$mental[AA234RAH$srh_115==6] <- "Valid skip"
AA234RAH$mental[AA234RAH$srh_115==7] <- "Don't know"
AA234RAH$mental[AA234RAH$srh_115==8] <- "Refusal"
AA234RAH$mental[AA234RAH$srh_115==9] <- "Not Stated"


ggplot(data = AA234RAH,aes(y=mental))+geom_bar()+theme_classic()+labs(x = "Number of people", y = "Situation of mental health", title = "Survey Mental health level")
```


```{r 108,fig.cap="General health",message=FALSE,echo=FALSE,warning=FALSE}
AA234RAH$body[AA234RAH$srh_110==1] <- "Exellent"
AA234RAH$body[AA234RAH$srh_110==2] <- "Very good"
AA234RAH$body[AA234RAH$srh_110==3] <- "Good"
AA234RAH$body[AA234RAH$srh_110==4] <- "Fair"
AA234RAH$body[AA234RAH$srh_110==5] <- "Poor"
AA234RAH$body[AA234RAH$srh_110==6] <- "Valid skip"
AA234RAH$body[AA234RAH$srh_110==7] <- "Don't know"
AA234RAH$body[AA234RAH$srh_110==8] <- "Refusal"
AA234RAH$body[AA234RAH$srh_110==9] <- "Not Stated"
ggplot(data = AA234RAH,aes(y=body))+geom_bar()+theme_classic()+labs(x = "Number of people", y = "Situation of general health", title = "Survey people's general health level")
```



```{r 105,fig.cap="ever physically assaulted by an adult in childhood (srh_115==5: poor mental health)",echo=FALSE,warning=FALSE}

AA234RAH$cex[AA234RAH$cexphys==1] <- "Never"
AA234RAH$cex[AA234RAH$cexphys==2] <- "Yes, at least once"
AA234RAH$cex[AA234RAH$cexphys==6] <- "Valid skip"
AA234RAH$cex[AA234RAH$cexphys==7] <- "Don’t know"
AA234RAH$cex[AA234RAH$cexphys==8] <- "Refusal"
AA234RAH$cex[AA234RAH$cexphys==9] <- "Not stated"
physex <- AA234RAH %>% ggplot(aes(x=cex,fill=srh_115==5)) + geom_bar() + theme_classic()+labs(x = "ever physically assaulted by an adult" , y = "count",title = " physically assaulted & mental condition")
physex
```



```{r 106,fig.cap="about number of friends and mental health", message=FALSE,echo=FALSE,warning=FALSE}
firend <- AA234RAH %>% filter(isl_100<=200 & srh_115 < 6) 
firend$mental[firend$srh_115==1] <- "Exellent"
firend$mental[firend$srh_115==2] <- "Very good"
firend$mental[firend$srh_115==3] <- "Good"
firend$mental[firend$srh_115==4] <- "Fair"
firend$mental[firend$srh_115==5] <- "Poor"

ggplot(data = firend, aes(x = mental, y = isl_100))+geom_boxplot()+theme_classic()+labs(x = "statement of mental level", y = "Number of close firends", title = " Mental health level and the number of firends")
```

```{r 109,fig.cap="work of local police",message=FALSE,echo=FALSE,warning=FALSE}
AA234RAH$plp130[AA234RAH$plp_130==1] <- "Good job"
AA234RAH$plp130[AA234RAH$plp_130==2] <- "Average job"
AA234RAH$plp130[AA234RAH$plp_130==3] <- "Poor job"
AA234RAH$plp130[AA234RAH$plp_130==6] <- "Valid skip"
AA234RAH$plp130[AA234RAH$plp_130==7] <- "Don't know"
AA234RAH$plp130[AA234RAH$plp_130==8] <- "Refusal"
AA234RAH$plp130[AA234RAH$plp_130==9] <- "Not stated"

ggplot(data = AA234RAH,aes(y=plp130))+geom_bar()+theme_classic()+labs(x = "Number of people", y = "Work done by Local Police", title = "Survey local police being approachable and easy to talk to")

```

```{r 111, fig.cap = "VIF of model",message=FALSE,echo=FALSE,warning=FALSE}
clean_data <- AA234RAH %>% filter(srh_115 < 6 & isl_100 <= 200)
#clean cbu_110 create new varibale cbu_110n
clean_data$cbu_110n[clean_data$cbu_110==1] <- 1
clean_data$cbu_110n[clean_data$cbu_110==2] <- 2
clean_data$cbu_110n[clean_data$cbu_110 > 2] <- 0
#clean cbu_140 create new varibale cbu_140n
clean_data$cbu_140n[clean_data$cbu_140==1] <- 1
clean_data$cbu_140n[clean_data$cbu_140==2] <- 2
clean_data$cbu_140n[clean_data$cbu_140 > 2] <- 0
#cexabu
clean_data$cexabun[clean_data$cexabu==1] <- 1
clean_data$cexabun[clean_data$cexabu==2] <- 2
clean_data$cexabun[clean_data$cexabu==3] <- 3
clean_data$cexabun[clean_data$cexabu > 3] <- 0
#cexphys
clean_data$cexphysn[clean_data$cexphys==1] <- 1
clean_data$cexphysn[clean_data$cexphys==2] <- 2
clean_data$cexphysn[clean_data$cexphys > 2] <- 0
#cexsex
clean_data$cexsexn[clean_data$cexsex==1] <- 1
clean_data$cexsexn[clean_data$cexsex==2] <- 2
clean_data$cexsexn[clean_data$cexsex > 2] <- 0
#cex_080
clean_data$cex_080n[clean_data$cex_080==1] <- 1
clean_data$cex_080n[clean_data$cex_080==2] <- 2
clean_data$cex_080n[clean_data$cex_080==3] <- 3
clean_data$cex_080n[clean_data$cex_080==4] <- 4
clean_data$cex_080n[clean_data$cex_080==5] <- 5
clean_data$cex_080n[clean_data$cex_080>5] <- 0
#drp_110
clean_data$drp_110n[clean_data$drp_110 ==1] <- 1
clean_data$drp_110n[clean_data$drp_110 ==2] <- 2
clean_data$drp_110n[clean_data$drp_110 ==3] <- 3
clean_data$drp_110n[clean_data$drp_110 ==4] <- 4
clean_data$drp_110n[clean_data$drp_110 ==5] <- 5
clean_data$drp_110n[clean_data$drp_110 ==6] <- 6
clean_data$drp_110n[clean_data$drp_110 ==7] <- 7
clean_data$drp_110n[clean_data$drp_110 > 7] <- 0
#drr_110
clean_data$drr_110n[clean_data$drr_110 ==1] <- 1
clean_data$drr_110n[clean_data$drr_110 ==2] <- 2
clean_data$drr_110n[clean_data$drr_110 ==3] <- 3
clean_data$drr_110n[clean_data$drr_110 ==4] <- 4
clean_data$drr_110n[clean_data$drr_110 ==5] <- 5
clean_data$drr_110n[clean_data$drr_110 ==6] <- 6
clean_data$drr_110n[clean_data$drr_110 ==7] <- 7
clean_data$drr_110n[clean_data$drr_110 > 7] <- 0
#dup_100
clean_data$dup_100n[clean_data$dup_100 ==1] <- 1
clean_data$dup_100n[clean_data$dup_100 ==2] <- 2
clean_data$dup_100n[clean_data$dup_100 > 2] <- 0
#dur_100
clean_data$dur_100n[clean_data$dur_100 ==1] <- 1
clean_data$dur_100n[clean_data$dur_100 ==2] <- 2
clean_data$dur_100n[clean_data$dur_100 > 2] <- 0
#dur_110
clean_data$dur_110n[clean_data$dur_110 ==1] <- 1
clean_data$dur_110n[clean_data$dur_110 ==2] <- 2
clean_data$dur_110n[clean_data$dur_110 > 2] <- 0
#hom_10
clean_data$hom_10n[clean_data$hom_10 ==1] <- 1
clean_data$hom_10n[clean_data$hom_10 ==2] <- 2
clean_data$hom_10n[clean_data$hom_10 > 2] <- 0

model_full_1.0 <- lm(clean_data$srh_115 ~ clean_data$isl_100 + clean_data$cbu_110n + clean_data$cbu_140n + clean_data$cexabun + clean_data$cexphysn + clean_data$cexsexn + clean_data$cex_080n + clean_data$drp_110n + clean_data$drr_110n + clean_data$dup_100n + clean_data$dur_100n + clean_data$dur_110n + clean_data$hom_10n)
vif(model_full_1.0)

```


```{r 112, fig.cap = "table of model",message=FALSE,echo=FALSE,warning=FALSE}
modeldur100 <- lm(clean_data$srh_115 ~ clean_data$isl_100 + 
    clean_data$cbu_110n + clean_data$cexphysn + 
    clean_data$cex_080n + clean_data$drr_110n + 
    clean_data$dup_100n + clean_data$dur_100n + 
    clean_data$hom_10n)
summary(modeldur100)
```



```{r 115, fig.cap = "table of education model",message=FALSE,echo=FALSE,warning=FALSE}

edumodel <- AA234RAH %>% filter(ehg3_01 < 8 & eduf10 < 11 & edum10 < 11 & edupr10 < 11 & wet_110 < 53 & whw_120 < 200) 

newmodel <- lm(edumodel$ehg3_01 ~ edumodel$eduf10 + edumodel$edum10 + edumodel$edupr10 + 
    edumodel$whw_120)
summary(newmodel)
```


```{r 116, fig.cap = "Plot of education model",message=FALSE,echo=FALSE,warning=FALSE}
par(mfrow = c(2,2))
plot(newmodel)
```



\newpage
# Appendix




\newpage
# Reference
